#ifndef PROJECT_CONF_H_
#define PROJECT_CONF_H_

#define IEEE802154_CONF_PANID 0xabcd

#define LOG_CONF_LEVEL_IPV6 LOG_LEVEL_WARN
#define LOG_CONF_LEVEL_RPL LOG_LEVEL_WARN
#define LOG_CONF_LEVEL_TCPIP LOG_LEVEL_WARN

#endif /* PROJECT_CONF_H_ */
